version: '3.9'

networks:
  app-network:
    driver: bridge
    
services:

  mongoserver:
    image: mongo:latest
    container_name: mongoserver
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - app-network
  
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: C23l10a1985
      MYSQL_USER: gfmaurila
      MYSQL_PASSWORD: C23l10a1985
      MYSQL_DATABASE: gfmaurila
    restart: always
    expose:
      - 3306
    ports:
      - "3306:3306"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass C23l10a1985
    restart: always
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - app-network

  oracle:
    image: oracleinanutshell/oracle-xe-11g
    environment:
      ORACLE_ALLOW_REMOTE: true
      ORACLE_DISABLE_ASYNCH_IO: true
      ORACLE_USER: gfmaurila
      ORACLE_PASSWORD: C23l10a1985
      ORACLE_DATABASE: gfmaurila
    restart: always
    expose:
      - 1521
    ports:
      - "1521:1521"
    networks:
      - app-network

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: gfmaurila
      POSTGRES_PASSWORD: C23l10a1985
      POSTGRES_DB: gfmaurila
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    cap_add: [ 'SYS_PTRACE' ]
    hostname: mssql
    container_name: sqlserver
    restart: always
    expose:
      - 1433
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=@C23l10a1985
    networks:
      - app-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    restart: always
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - app-network

  # Kafka
  zookeeper:
    image: 'zookeeper:3.7'
    container_name: 'zookeeper'
    restart: always
    ports:
      - 2181:2181
    networks:
      - app-network

  # Kafka
  kafka:
    image: 'confluentinc/cp-kafka:latest'
    container_name: 'kafka'
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network

    