version: '3.9'

networks:
  app-oracle-network:
    driver: bridge

services:
  
  oracle:
    image: oracleinanutshell/oracle-xe-11g
    environment:
      ORACLE_ALLOW_REMOTE: true
      ORACLE_DISABLE_ASYNCH_IO: true
      ORACLE_USER: gfmaurila
      ORACLE_PASSWORD: C23l10a1985
      ORACLE_DATABASE: gfmaurila
    restart: always
    expose:
      - 1521
    ports:
      - "1521:1521"
    networks:
      - app-oracle-network
