version: '3.9'

networks:
  app-kafka-network:
    driver: bridge

services:

  zookeeper:
    image: 'zookeeper:3.7'
    container_name: 'zookeeper'
    restart: always
    ports:
      - 2181:2181
    networks:
      - app-kafka-network

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    container_name: 'kafka'
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-kafka-network
